### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by NewmanDaniel** [stephen-cd/MAtimeclock#16]
If you add or edit a work session, it should let you do another and when you edit another the start time should reflect the session instead of the last one edited

**Comment by stephen-cd** [comment]
Bug 1: After adding or editing work session, you can't go to the add or edit work session pages.
What happens: you click either button and the graph moves up a little and the page doesn't change.

Bug 2 (may require fixing bug 1 first to see): After adding or editing work session, when you go to edit a different work session, the start time listed in the input is the start time from the previous session.

Bug 2 might not be triggered by adding sessions, might just be from editing, can't remember.
